server:
  port: 8888
spring:
  application:
    name: gitconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanggja/springcloud.git
          search-paths: config
          username: wanggja
          password: gaoJIAN123456
        default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka

