server:
  port: 8888
spring:
  application:
    name: gitconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanggja/springcloud
          username: wanggja
          password: gaoJIAN123456
          search-paths: config
          default-label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

