server:
  port: 8888
spring:
  application:
    name: gitconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanggja/springcloud.git
          searchPaths: config
          username: wanggja
          password: gaoJIAN123456
        label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

